export const themes = {
  // Default theme - dark green + gold, refined from the icon artwork's navy/gold/teal palette.
  // The accent gold here is intentionally deeper/more saturated than the icon's pale linework
  // gold: that pale tone (#E9D09E) reads fine as thin decorative linework on navy, but used as a
  // solid button fill with white icons/text on top, it didn't have enough contrast - white was
  // "missing its color" against it. This deeper gold fixes that while staying warm/gold in feel.
  sibyl: {
    key: 'sibyl',
    label: 'Sibyl (Dark)',
    isDark: true,
    bg: '#0D1B14',
    surface: '#142A1F',
    surfaceAlt: '#1C3B2A',
    border: '#2A4A38',
    text: '#F3ECDC',
    textMuted: '#8FA895',
    accent: '#C9973F',
    accentDeep: '#A67C2E',
    teal: '#3FAE8A',
    tealDeep: '#2C7A5F',
    danger: '#E38585',
    success: '#6FC2A6',
    waveform: '#3FAE8A',
    waveformMuted: '#33443C',
  },
  midnight: {
    key: 'midnight',
    label: 'Midnight (Dark)',
    isDark: true,
    bg: '#0F1115',
    surface: '#1B1E24',
    surfaceAlt: '#242832',
    border: '#2E323C',
    text: '#F2F3F5',
    textMuted: '#9AA0AC',
    accent: '#E5605A',
    waveform: '#E5605A',
    waveformMuted: '#3A3F4A',
  },
  paper: {
    key: 'paper',
    label: 'Paper (Light)',
    isDark: false,
    bg: '#FBF6EE',
    surface: '#FFFFFF',
    surfaceAlt: '#F3ECDD',
    border: '#E7DDC7',
    text: '#2B2620',
    textMuted: '#8A8070',
    accent: '#C1502E',
    waveform: '#C1502E',
    waveformMuted: '#E0D6C0',
  },
  slate: {
    key: 'slate',
    label: 'Slate (Light)',
    isDark: false,
    bg: '#F4F6F8',
    surface: '#FFFFFF',
    surfaceAlt: '#E9EDF1',
    border: '#DCE2E8',
    text: '#20242A',
    textMuted: '#767E88',
    accent: '#3A6DE0',
    waveform: '#3A6DE0',
    waveformMuted: '#D6DCE2',
  },
  sand: {
    key: 'sand',
    label: 'Sand (Light)',
    isDark: false,
    bg: '#F7F1E8',
    surface: '#FFFDF8',
    surfaceAlt: '#EFE4D2',
    border: '#E3D5BC',
    text: '#3A2F22',
    textMuted: '#8F7E64',
    accent: '#B8813A',
    waveform: '#B8813A',
    waveformMuted: '#E6D8BE',
  },
};

export const themeList = Object.values(themes);
export const DEFAULT_THEME_KEY = 'sibyl';
